language: go
go:
- 1.4
install:
- go get github.com/spf13/hugo
script: hugo -t projecthub
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: outside.osgav.run
  region: eu-central-1
  endpoint: outside.osgav.run.s3-website.eu-central-1.amazonaws.com
  local-dir: public
  skip_cleanup: true
  acl: public_read
  on:
    repo: osgav/osgav-outside
