version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0
  aws-s3: circleci/aws-s3@3.1.1

workflows:
  sample:
    jobs:
      - hugo/build:
          version: "0.48"
          html-proofer: false
          post-steps:
            - run: echo helloworld
            - aws-s3/copy:
                from: public/
                to: s3://sample-app-vue
                arguments: --recursive
