version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0
  aws-s3: circleci/aws-s3@3.1.1

workflows:
  build_and_deploy:
    jobs:
      - hugo/build
      - deploy

jobs:
  hugo/build:
    version: "0.48"
    html-proofer: false
    post-steps:
      - run: echo "end of hugo build job"
  deploy:
    docker:
      - image: cimg/aws:2023.01
    steps:
      - aws-s3/copy:
          from: public/
          to: s3://sample-app-vue
          arguments: --recursive


    #jobs:
    #  - hugo/build:
    #      version: "0.48"
    #      html-proofer: false
    #      post-steps:
    #        - run: echo "trying non-alpine image..."
    #        - aws-s3/copy:
    #            from: public/
    #            to: s3://sample-app-vue
    #            arguments: --recursive

# maybe this config is not invalid...

