version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0
  aws-s3: circleci/aws-s3@3.1.1

jobs:
  deploy:
    docker:
      - image: cimg/aws:2023.01
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: check build output
          command: ls /tmp/workspace/public
      - aws-s3/copy:
          from: /tmp/workspace/public/
          to: s3://outside.osgav.run/circleci-test01
          arguments: --recursive

workflows:
  version: 2
  main:
    jobs:
      - hugo/build:
          version: "0.48"
          html-proofer: false
      - deploy:
          requires:
            - hugo/build

