version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0
  aws-cli: circleci/aws-cli@3.1.4
  aws-s3: circleci/aws-s3@3.1.1

jobs:
  deploy:
    docker:
      - image: cimg/aws:2023.01
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: check build output 01
          command: ls -R /tmp/workspace/public
      - run:
          name: run post-build-script.sh
          command: ./build/post-build-script.sh
          working_directory: /tmp/workspace
      - run:
          name: check build output 02
          command: ls -R /tmp/workspace/public
      - aws-cli/setup:
          role-arn: "arn:aws:iam::698362578618:role/oidc-circleci-osgav-outside"
      - aws-s3/copy:
          install-aws-cli: false
          from: /tmp/workspace/public/
          to: s3://outside.osgav.run/
          arguments: --recursive

workflows:
  version: 2
  main:
    jobs:
      - hugo/build:
          version: "0.48"
          html-proofer: false
          post-steps:
            - persist_to_workspace:
                root: .
                paths:
                  - build/
      - deploy:
          requires:
            - hugo/build
          context:
            - oidc
          filters:
            branches:
              only: master

